### ISSUE TITLE
Dashing not going forward consistently

### ISSUE THREAD

**Issue by achongco** [jellesse92/Project13#52]
Appears only to effect X velocity. If removing VelocityX(0) and VelocityY(0) from the end of the dashing function, the player continues their upward movement but horizontal movement is limited. 

Might be due to the Movement Function changing the x but not the y velocity. Commenting it out makes the influence of VelocityX(0)'s apparent.

**Comment by clpachec** [comment]
I think it's a collision problem. It only started when you implemented the follow along ground

**Comment by clpachec** [comment]
Ohhhhh happens if deactivated velocity is on

**Comment by clpachec** [comment]
Just add activate velocity to the dash

**Comment by achongco** [comment]
ohh
